package com.moon.domain;

// Generated 2014-9-28 13:03:56 by Hibernate Tools 3.4.0.CR1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 1443022112102539669L;
	private int id;
	private String city;
	private String street;
	private String province;
	private String zipcode;
	private Customers customers;

	public Address() {
	}

	public Address(int id, String city, String street, String province,
			String zipcode) {
		this.id = id;
		this.city = city;
		this.street = street;
		this.province = province;
		this.zipcode = zipcode;
	}

	public Address(int id, String city, String street, String province,
			String zipcode, Customers customers) {
		this.id = id;
		this.city = city;
		this.street = street;
		this.province = province;
		this.zipcode = zipcode;
		this.customers = customers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public Customers getCustomers() {
		return customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	@Override
	public String toString() {
		return id + " " + city + " " + street + " " + province + " " + zipcode;
	}
}
